server:
  port: 8021
spring:  application:    name: COLLEGE-SERVICE
    
Eureka:
   client:
    register-with-eureka: true
    fetch-registery: true
    server-url:
      defaultZone: http://localhost:8761/eureka
      hostname: localhost